### ISSUE TITLE
ImportError: No module named yattag

### ISSUE THREAD

**Issue by Novel-Idea** [aref993/Journey-To-DayOne-converter#2]
I'm getting a consistent problem when running the script resulting in the following error:

`Traceback (most recent call last):
  File "/Users/ryanandlisa/Documents/Journal Transition/journey/JourneyTools.py", line 9, in <module>
    from yattag import Doc, indent
ImportError: No module named yattag`

When you say 

> extract zip archive to a folder named journey
> move JourneyTools.py and journey folder to same location

Do you mean that both journey (the extracted folder from the zip) and JourneyTools.py should be within the same folder (IE, only the extracted folder and script) or that JourneyTools.py should be in the folder where the images and jsons were extracted?

I'm assuming this program was designed to handle multiple Journey entries, as well. 

In an attempt to troubleshoot, I've installed both Python 2.7 and 3.7, but the error remains the same.

**Comment by myerzman** [comment]
I got the same error . File "JourneyTools.py", line 9, in <module>
    from yattag import Doc, indent

**Comment by kubaunold** [comment]
For me it was the fact, that `yattag` didn't work with Python 3.7 (only up to 3.5). So I removed the module
`pip uninstall yattag`
Then installed it once again, this time making sure I use `pip`, not `pip3` command
`pip install yattag`
Now I was able to run my file w/out any problems by: (of course after switching my compiler to Python 2.7)
`python .\main.py`

**Comment by kylelindgren** [comment]
I also had luck using python2.7

`pip2 install yattag`
